on: push
name: 🚀 Deploy Main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
   
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.main_server }}
        username: wwwftp
        password: ${{ secrets.ftp }}
        protocol: ftp
        server-dir: /theguestwifi/
        exclude: '[**/.git*, **/.git*/**, LICENSE, README.md, theguestwifi, theguestwifi.rsc]'
